//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLECCION()
        {
            this.EJEMPLAR = new HashSet<EJEMPLAR>();
            this.GENEROCOLECCION = new HashSet<GENEROCOLECCION>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_tipocoleccion { get; set; }
    
        public virtual TIPOCOLECCION TIPOCOLECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EJEMPLAR> EJEMPLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENEROCOLECCION> GENEROCOLECCION { get; set; }
    }
}
