//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJEMPLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EJEMPLAR()
        {
            this.IDENTIFICADOREJEMPLAR = new HashSet<IDENTIFICADOREJEMPLAR>();
            this.IDIOMAEJEMPLAR = new HashSet<IDIOMAEJEMPLAR>();
            this.PRESTAMO = new HashSet<PRESTAMO>();
            this.RESERVA = new HashSet<RESERVA>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int codigo { get; set; }
        public string autor { get; set; }
        public System.DateTime f_publicacion { get; set; }
        public string nombre { get; set; }
        public int id_formatoejemplar { get; set; }
        public int id_editorialejemplar { get; set; }
        public int id_palabrasclave { get; set; }
        public int id_coleccion { get; set; }
    
        public virtual COLECCION COLECCION { get; set; }
        public virtual EDITORIALEJEMPLAR EDITORIALEJEMPLAR { get; set; }
        public virtual FORMATOEJEMPLAR FORMATOEJEMPLAR { get; set; }
        public virtual PALABRASCLAVE PALABRASCLAVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDENTIFICADOREJEMPLAR> IDENTIFICADOREJEMPLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDIOMAEJEMPLAR> IDIOMAEJEMPLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMO> PRESTAMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
