//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTO()
        {
            this.REGISTROASISTENCIA = new HashSet<REGISTROASISTENCIA>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string objetivo { get; set; }
        public string cantidad { get; set; }
        public int id_horarioevento { get; set; }
    
        public virtual HORARIOEVENTO HORARIOEVENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTROASISTENCIA> REGISTROASISTENCIA { get; set; }
    }
}
