//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENEROCOLECCION
    {
        public int id { get; set; }
        public string Fantasia { get; set; }
        public string CienciaFiccion { get; set; }
        public string Historia { get; set; }
        public string Realista { get; set; }
        public string Romantico { get; set; }
        public string Suspenso { get; set; }
        public string Policiaco { get; set; }
        public string Drama { get; set; }
        public string Psicologico { get; set; }
        public string Comedia { get; set; }
        public int id_coleccion { get; set; }
    
        public virtual COLECCION COLECCION { get; set; }
    }
}
