//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDENTIFICADOREJEMPLAR
    {
        public int id { get; set; }
        public string ISBN { get; set; }
        public string ISSN { get; set; }
        public string DOI { get; set; }
        public int codigo_ejemplar { get; set; }
    
        public virtual EJEMPLAR EJEMPLAR { get; set; }
    }
}
