//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.EFDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROYECTOv17Entities : DbContext
    {
        public PROYECTOv17Entities()
            : base("name=PROYECTOv17Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA> AREA { get; set; }
        public virtual DbSet<COLECCION> COLECCION { get; set; }
        public virtual DbSet<EDITORIALEJEMPLAR> EDITORIALEJEMPLAR { get; set; }
        public virtual DbSet<EJEMPLAR> EJEMPLAR { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<FORMATOEJEMPLAR> FORMATOEJEMPLAR { get; set; }
        public virtual DbSet<GENEROCOLECCION> GENEROCOLECCION { get; set; }
        public virtual DbSet<HORARIOAREA> HORARIOAREA { get; set; }
        public virtual DbSet<HORARIOEVENTO> HORARIOEVENTO { get; set; }
        public virtual DbSet<IDENTIFICADOREJEMPLAR> IDENTIFICADOREJEMPLAR { get; set; }
        public virtual DbSet<IDIOMAEJEMPLAR> IDIOMAEJEMPLAR { get; set; }
        public virtual DbSet<INSTITUCIONUSUARIO> INSTITUCIONUSUARIO { get; set; }
        public virtual DbSet<OCUPACIONUSUARIO> OCUPACIONUSUARIO { get; set; }
        public virtual DbSet<PALABRASCLAVE> PALABRASCLAVE { get; set; }
        public virtual DbSet<PRESTAMO> PRESTAMO { get; set; }
        public virtual DbSet<REGISTROASISTENCIA> REGISTROASISTENCIA { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SESION> SESION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TELEFONOUSUARIO> TELEFONOUSUARIO { get; set; }
        public virtual DbSet<TIPOCOLECCION> TIPOCOLECCION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
