//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMO
    {
        public int carnet_usuario { get; set; }
        public int codigo_ejemplar { get; set; }
        public System.DateTime f_h_prestamo { get; set; }
        public System.DateTime f_h_devolucion { get; set; }
    
        public virtual EJEMPLAR EJEMPLAR { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
