//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BINAES.Modelsv3
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJEMPLAR
    {
        public int codigo { get; set; }
        public string autor { get; set; }
        public System.DateTime f_publicacion { get; set; }
        public string nombre { get; set; }
        public int id_formatoejemplar { get; set; }
        public int id_editorialejemplar { get; set; }
        public int id_palabrasclave { get; set; }
        public int id_coleccion { get; set; }
    }
}
